#!/bin/bash

WORKDIR=~/projects/linux/vulns/cve/review/done

for f in `ls -1 ${WORKDIR}/mbox.*cve`; do
    version=$(echo ${f} | grep -o 6.7.[1-5])
    shas=$(grep -i upstream ${f} | grep -oE "[a-f0-9]{40,}")

    for s in ${shas}; do
        oneline=$(git --no-pager log --oneline -n1 ${s})
        echo ${oneline} | tee -a ${WORKDIR}/v${version}-greg
    done
done

