#!/bin/bash

WORKDIR=~/projects/google/toys/cve-review-results/results
INPUT=${WORKDIR}/v6.7..v6.7.1.txt

while read -r line; do
    echo "${line}"

    stable=$(echo ${line} | cut -d' ' -f1)
    mainline=$(git --no-pager log -n1 ${stable} | grep -i upstream ${f} | grep -oE "[a-f0-9]{40,}")
    git --no-pager log --oneline -n1 ${mainline} >> ${WORKDIR}/v6.7.1-lee
done < ${INPUT}
